name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download ngrok
        run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip

      - name: Extract ngrok
        run: unzip ngrok.zip

      - name: Auth
        run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable TS
        run: sudo sed -i 's/^#?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
          
      - name: Restart SSH service
        run: sudo service ssh restart

      - name: Create Tunnel
        run: ./ngrok/ngrok tcp 3389
